FROM python:3.9-slim

WORKDIR /app

# By copying over requirements first, we make sure that Docker will cache
# our installed requirements rather than reinstall them on every build
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8000
ENTRYPOINT ["python3"]