version: '3.7'
services:
  http_consumer_server:
    container_name: "http_consumer_server"
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./http_communication/consumer:/app/src/
    entrypoint: ["/bin/sh", "-c", "sanic src.server.app --host 0.0.0.0 --port 8080 --workers=2" ]
  http_producer_server:
    container_name: "http_producer_server"
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./http_communication/producer:/app/src/
    entrypoint: ["/bin/sh", "-c", "sanic src.server.app --host 0.0.0.0 --port 8081 --workers=2" ]
  locust:
    container_name: "locust"
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./http_communication/locust:/app/locust
      - ./http_communication/run_locust.sh:/app/run_locust.sh
      - ./data:/app/data
    entrypoint: ["/bin/sh", "run_locust.sh" ]
networks 

