// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package lsp_db

import (
	"database/sql"
)

type Document struct {
	ID     int64
	Path   string
	TreeID int64
	Code   string
}

type Pyenv struct {
	ID            int64
	OsName        string
	PyName        sql.NullString
	PyRow         sql.NullInt64
	PyStartColumn sql.NullInt64
	PyEndColumn   sql.NullInt64
	PyDocumentID  sql.NullInt64
}

type Yamlenv struct {
	ID              int64
	OsName          string
	YamlRow         sql.NullInt64
	YamlStartColumn sql.NullInt64
	YamlEndColumn   sql.NullInt64
	YamlDocumentID  sql.NullInt64
}
