version: '3'
services:
  notebook:
    volumes:
      - .:/home/jovyan
    build:
      context: .
      dockerfile: all_services/notebook_docker/Dockerfile
    ports:
      - "8888:8888"
  python:
    entrypoint:
      - python
    build:
      context: .
      dockerfile: all_services/python_docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app